services:
  - type: web
    name: inf8808-equipe19
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
